setopt NO_HUP
setopt interactivecomments

autoload -Uz compinit && compinit
bindkey -v

show_logos=("fastfetch" "pokemon-colorscripts -r --no-title")
$(shuf -n1 -e "${show_logos[@]}")
echo "\n"

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

zinit ice lucid wait"0" atclone"sed -ie 's/fc -rl 1/fc -rli 1/' shell/key-bindings.zsh" \
  atpull"%atclone" multisrc"shell/{completion,key-bindings}.zsh" id-as junegunn/fzf_completions \
  pick"/dev/null"
zinit light junegunn/fzf

zinit snippet PZT::modules/history/init.zsh

zinit light Aloxaf/fzf-tab
zinit ice wait'0' blockf lucid; zinit light zsh-users/zsh-completions
zinit ice lucid wait"1" lucid atload"!_zsh_autosuggest_start"; zinit load zsh-users/zsh-autosuggestions
zinit ice from'gh-r' as'program'; zinit light sei40kr/fast-alias-tips-bin
zinit light sei40kr/zsh-fast-alias-tips
zinit light zdharma-continuum/fast-syntax-highlighting
zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit light mafredri/zsh-async

alias f=yy # yazi file manager
alias e=$EDITOR
alias ee='neovide&'
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias mkdir='mkdir -p'
alias tm='tmux'
alias ldr=lazydocker
alias g=lazygit
alias jy='convfmt -f json -t yaml'

# aurhelper='paru'
aurhelper='yay'
alias pi='$aurhelper'       # install package
alias pu='$aurhelper -Rns'  # uninstall package
alias pup='$aurhelper -Syu' # update system/package/aur
alias pl='$aurhelper -Qs'   # list installed package
alias pa='$aurhelper -Ss'   # list availabe package
alias pc='$aurhelper -Sc'   # remove unused cache
alias po='$aurhelper -Qtdq | $aurhelper -Rns -' # remove unused packages
alias cs=coursier

## Editor mode
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^v' edit-command-line
bindkey -M vicmd '^v' edit-command-line
bindkey jk vi-cmd-mode

## Vi mode
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]]  ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]]     ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
echo -ne '\e[5 q'
preexec() {
  echo -ne '\e[5 q'
}

eval "$(zoxide init zsh --cmd j)"
alias zi=__zoxide_zi $@

## yazi file manager
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

## p10k, to customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
